import Head from 'next/head'
import SimpleSidebar from '@/components/sidebar'
import Simple from '@/components/navbar'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Simple/> 
      </main>
    </>
  )
}
