import Head from 'next/head'
// import CallToActionWithAnnotation from '@/components/body'
// import SmallWithSocial from '@/components/footer'
// import WithBackgroundImage from '@/components/body'
// import LargeWithLogoLeft from '@/components/footer'
import SimpleSidebar from '@/components/sidebar'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SimpleSidebar/>
      </main>
    </>
  )
}
